version: "3"
services:
  dnsmasq: # https://unix.stackexchange.com/questions/676942
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "53:53"
    cap_add:
      - NET_ADMIN
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=bar
    logging:
      options:
        max-size: 100m
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./self_dnsmasq_addn_hosts:/etc/self_dnsmasq_addn_hosts
      - ./static-hosts.conf:/etc/static-hosts.conf
    # - ./dnsmasq.log:/var/log/dnsmasq.log
      - /etc/localtime:/etc/localtime:ro
